# fly.toml app configuration file generated for zunifortyfourthbe on 2023-05-27T09:59:11-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "zunifortyfourthbe"
primary_region = "dfw"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
